---
title: "STAT443"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
library(faraway)
gt <- read_csv("gt_2012 (1).csv")
pairs(gt, col = "red")

```

```{r}
head(gt)
model1 <- lm(cbind(CO,NOX) ~ ., data = gt)
```
```{r}
model2 <- lm(CO ~., data = gt)
vif(model2)
```

```{r}
#Partial Correlation Coefficient between CO and AT
model2.1 <-lm(CO ~.-AT, data = gt)
model2.2 <-lm(AT ~. - CO, data = gt)
cor(resid(model2.1), resid(model2.2))#Result Small, can remove the variable from the model  
```

```{r}
#Partial Correlation Coefficient between CO and GTEP
model2_1 <-lm(CO ~.-GTEP, data = gt)
model2_2 <-lm(GTEP ~. - CO, data = gt)
cor(resid(model2_1), resid(model2_2))#Result Small 
```
```{r}

```

```{r}
#Partial Correlation Coefficient between CO and TIT
model2_a <-lm(CO ~.-TIT, data = gt)
model2_b <-lm(TIT ~. - CO, data = gt)
cor(resid(model2_a), resid(model2_b))#Result Small, can remove the variable from the model  
```
```{r}
```

```{r}
#Partial Correlation Coefficient between CO and TIT
model2_a <-lm(CO ~.-TIT, data = gt)
model2_b <-lm(TIT ~. - CO, data = gt)
cor(resid(model2_a), resid(model2_b))#Result Small, can remove the variable from the model  
```
```{r}
#Partial Correlation Coefficient between CO and TAT
model2_c <-lm(CO ~.-TAT, data = gt)
model2_d <-lm(TAT ~. - CO, data = gt)
cor(resid(model2_c), resid(model2_d))#Result Small, can remove the variable from the model  
```

```{r}
#Partial Correlation Coefficient between CO and TEY
model2_e <-lm(CO ~.-TEY, data = gt)
model2_f <-lm(TEY ~. - CO, data = gt)
cor(resid(model2_e), resid(model2_f))#Result Small,can remove the variable from the model   
```

```{r}
#Partial Correlation Coefficient between CO and CDP
model2_g <-lm(CO ~.-CDP, data = gt)
model2_h <-lm(CDP ~. - CO, data = gt)
cor(resid(model2_g), resid(model2_h))#Result Small,can remove the variable from the model   
```

```{r}
summary(model2)$r.squared
modela_r <- lm(CO ~ AP + AH + AFDP + NOX, data = gt)
summary(modela_r)$r.squared # Not Feasible 
```
```{r}
model3 <- lm(CO ~.-NOX, data = gt)
summary(model3)
summary(model3)$r.squared
```

```{r}
vif(model3)
```

```{r}
model4 <- lm(NOX ~., data = gt)
summary(model4)
summary(model4)$r.squared
model5 <- lm(NOX ~. - CO, data = gt)
summary(model5)
summary(model5)$r.squared
```
```{r}
vif(model2)#model2 <- lm(CO ~., data = gt)
vif(model_4)#model4 <- lm(NOX ~., data = gt)

vif(model3)#model3 <- lm(CO ~.-NOX, data = gt)
vif(model5)#model5 <- lm(NOX ~. - CO, data = gt)
```

