---
title: "STAT 443 Final Project - Mid-Range Data Analysis"
author: "Jackie Kang, Jonas Reger | Glosemeyer"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: cosmo
    # code_folding: hide
    # toc: true
    # toc_float:
    #   collapsed: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn=-1)
```

<style>
div.blue {background-color:#e6f0ff; border-radius: 0px; padding: 20px;}
code {color: red;}
</style>

# Import Packages

```{r import packages}
suppressMessages(library(tidyverse))
suppressMessages(library(MASS))
suppressMessages(library(faraway))
suppressMessages(library(leaps))
```

# Import Data

```{r import data}
gt_2012 <- read_csv("gt_2012.csv")
```

```{r mid range data}
gt_mid_all <- gt_2012 %>% filter(TEY >= 130 & TEY <=136)
gt_mid <- subset(gt_mid_all, select = -NOX)
head(gt_mid)
```

# Model Diagnostics

```{r full model}
mid1 <- lm(CO ~., data = gt_mid)
summary(mid1)
v = vif(mid1)
v[which(v > 5)]
```

```{r correlation check, eval=F}
pairs(gt_mid, pch=20, col="#13294b")
round(cor(gt_mid),2)
# AT & GTEP: 0.95
# AT & TIT: 0.89
# AT & CDP
# GTEP & TIT 
# CDP & TIT 
# GTEP & CDP
```

```{r partial correlation}
### Partial Correlation Coefficient between CO and AT
mod1a <-lm(CO ~.-AT, data = gt_mid)
mod1b <-lm(AT ~. - CO, data = gt_mid)
# Result Small, can remove the variable from the model  
cor(resid(mod1a), resid(mod1b))

### Partial Correlation Coefficient between CO and GTEP
mod1c <-lm(CO ~.-GTEP, data = gt_mid)
mod1d <-lm(GTEP ~. - CO, data = gt_mid)
# Result Small, can remove the variable from the model 
cor(resid(mod1c), resid(mod1d))

### Partial Correlation Coefficient between CO and CDP
mod1e<-lm(CO ~.-CDP, data = gt_mid)
mod1f <-lm(CDP ~. - CO, data = gt_mid)
# Result Small, can remove the variable from the model   
cor(resid(mod1f), resid(mod1e))

### Partial Correlation Coefficient between CO and TIT
mod1h <-lm(CO ~.-TIT, data = gt_mid)
mod1g <-lm(TIT ~. - CO, data = gt_mid)
# Result Small, can remove the variable from the model  
cor(resid(mod1h), resid(mod1g))
```


```{r modle without GTEP}
mid2 <- lm(CO ~. - GTEP, data = gt_mid)
summary(mid2)
v = vif(mid2)
v[which(v > 5)]
```

```{r comparing mod1 and mod2}
anova(mid2, mid1)#mod2 is better 
```

```{r model 3}
mid3 <- lm(CO ~. - GTEP - TIT - AT, data = gt_mid)
summary(mid3)
v = vif(mid3)
v[which(v > 5)]
```

```{r}
mid4_aic_back <- step(mid1, trace = FALSE)
summary(mid4_aic_back) #REMOVE GTEP & TEY 
```

```{r}
anova(mid4_aic_back, mid2)#mid4_aic_back
```

```{r}
mid5 <- lm(CO ~ AT + AP + AH + poly(AFDP,2) + poly(TIT,2) + poly(TAT,2) + poly(CDP,2),data = gt_mid)

# boxcox transformation didn't help model
# boxcox(mid5, lambda = seq(0.25, 0.5, length.out=100))

summary(mid5) #ambient variable may not have strong influence over CO emission 
v = vif(mid5)
v[which(v > 5)]
```

```{r}
mid6_back_aic = step(mid5, trace = FALSE)
summary(mid6_back_aic)
```

```{r}
mod1 <- lm(CO~1, data = gt_mid)
mid6_aic_both = step(
  mod1,
  scope = CO ~ poly(AT,2) + poly(AP,2) + poly(AH,2) + poly(AFDP, 2) + poly(TIT, 2) + 
    poly(TAT, 2) + poly(CDP, 2),
  direction = 'both', trace = FALSE
)
summary(mid6_aic_both)
```


```{r}
v = vif(mid6_aic_both)
v[which(v > 5)]
```

```{r}
abplot = function(X, Y, Xa, Ya, Xo, Yo, c){
  sX = sd(X); sY = sd(Y); r = cor(X, Y); m = sY/sX*r
  sXa = sd(Xa); sYa = sd(Ya); ra = cor(Xa, Ya); ma = sYa/sXa*ra
  mX = mean(X); mY = mean(Y)
  mXa = mean(Xa); mYa = mean(Ya)
  yint = mY - mX*m
  yinta = mYa - mXa*ma
  plot(X, Y, pch=20, col="#13294b")
  points(Xo, Yo, pch=20, col=c)
  abline(yint, m, col="dodgerblue", lty=2, lwd=2)
  abline(yinta, ma, col="#e84a27", lwd=2)
}
```


```{r}
critval = qt(0.05/(2*nobs(mid5)), df=df.residual(mid5)-1, lower=FALSE)
out_ind = which(abs(rstudent(mid5)) > critval)
out_ind

gt_adj = gt_mid[-c(out_ind)[c(3, 8)],]
mid5_adj = update(mid5, data=gt_adj)
# mod.diag(fit1_adj, "Adjusted Fit1 data model")

gt_out = gt_mid[c(out_ind),]
print("potential outlier observations")
gt_out

c = rep("dodgerblue", 8); c[c(3, 8)] = "#e84a27"

par(mfrow = c(2, 2))
abplot(gt_mid$AT, gt_mid$CO, gt_adj$AT, gt_adj$CO, gt_out$AT, gt_out$CO, c)
abplot(gt_mid$AP, gt_mid$CO, gt_adj$AP, gt_adj$CO, gt_out$AP, gt_out$CO, c)
abplot(gt_mid$AH, gt_mid$CO, gt_adj$AH, gt_adj$CO, gt_out$AH, gt_out$CO, c)
abplot(gt_mid$AFDP, gt_mid$CO, gt_adj$AFDP, gt_adj$CO, gt_out$AFDP, gt_out$CO, c)
abplot(gt_mid$GTEP, gt_mid$CO, gt_adj$GTEP, gt_adj$CO, gt_out$GTEP, gt_out$CO, c)
abplot(gt_mid$TIT, gt_mid$CO, gt_adj$TIT, gt_adj$CO, gt_out$TIT, gt_out$CO, c)
abplot(gt_mid$TAT, gt_mid$CO, gt_adj$TAT, gt_adj$CO, gt_out$TAT, gt_out$CO, c)
abplot(gt_mid$CDP, gt_mid$CO, gt_adj$CDP, gt_adj$CO, gt_out$CDP, gt_out$CO, c)
abplot(gt_mid$TEY, gt_mid$CO, gt_adj$TEY, gt_adj$CO, gt_out$TEY, gt_out$CO, c)
```



```{r}
5/3097 < 0.01
str(gt_mid)
str(gt_adj)
```

```{r}
#BEST SO FAR
mid5_no <- lm(CO ~ AT + AP + AH + poly(AFDP,2) + poly(TIT,2) + poly(TAT,2) + poly(CDP,2),data = gt_adj)
summary(mid5_no) #ambient variable may not have strong influence over CO emission 
vif(mid5_no)
```


```{r}
suppressMessages(library(lmtest))
suppressMessages(library(boot))
#write diagnostic functions for later use 
#Fitted VS Residual Test 
test_FvsR = function(model){
plot(fitted(model), resid(model), xlab = "Fitted", ylab = "Residuals", main = "Residual Plot", col = "#13294b", pch=20)
abline(h = 0, col = "#e84a27")}
#QQ plot & QQline
test_qq = function(model){
qqnorm(resid(model), main = "Normal Q-Q plot", col = "#13294b", pch=20)
qqline(resid(model), col = "#e84a27")
}
#BP test 
test_bp = function(model, alpha) {
  p_val = bptest(model)$p.value
  decision = ifelse(p_val < alpha,"Reject", "Fail to Reject")
  list1 = list(bp.p_val = p_val, bp.decision = decision)
  return(list1)
}
# Shapiro–Wilk test (sw test)
test_sw = function(model, alpha) {
  p_val = shapiro.test(resid(model))$p.value
  decision = ifelse(p_val < alpha,"Reject", "Fail to Reject")
  list1 = list(sw.p_val = p_val, sw.decision = decision)
  return(list1)
}
#Calculate loocv_rmse
get_loocv_rmse = function(model) {
  sqrt(mean((resid(model) / (1 - hatvalues(model))) ^ 2))
}
#Calculate adr2
get_adj_r2 = function(model) {
  summary(model)$adj.r.squared
}
#Get number of parameters 
get_num_params = function(model) {
  length(coef(model))
}
```

```{r}
#Run All Test Diagnostic
run_all_diagnostic = function(model, visual=TRUE, alpha=0.05){
  if (visual) {
    par(mfrow = c(1,2))
    test_FvsR(model)
    test_qq(model)
  }
  loocv_rmse = get_loocv_rmse(model)
  adj.r.squared = get_adj_r2(model)
  params = get_num_params(model)
  bp = test_bp(model, alpha)
  sw = test_sw(model, alpha)
  data_frame = data.frame(loocv_rmse, adj.r.squared, params, bp, sw, row.names = '')
  return(data_frame)
}
```

```{r}
run_all_diagnostic(mid5)
```

```{r}
par(mfrow=c(2,2))
plot(mid5)
```

```{r}
par(mfrow=c(2,2))
plot(mid5_no)
```

```{r}
boxcox(mid5_no)
```

```{r}
mid5_no <- lm(sqrt(CO)  ~ AT + AP + AH + poly(AFDP,2) + poly(TIT,2) + poly(TAT,2) + poly(CDP,2),data = gt_adj)
summary(mid5_no) #ambient variable may not have strong influence over CO emission 
vif(mid5_no)
```

```{r}
gt_adj_all = gt_mid[-c(out_ind),]
mod1 <- lm(CO~., data = gt_adj_all)
mid1_aic_back = step(mod1, trace = FALSE)
summary(mid1_aic_back)
vif(mid1_aic_back)
```

```{r}
boxcox(mid1_aic_back)
```

```{r}
par(mfrow=c(2,2))
plot(mod1)
```

```{r}
midbest1 <- lm(CO ~ AT + AP + AH + poly(AFDP,2) + poly(TIT,2) + poly(TAT,2) + poly(CDP,2),data = gt_mid)
summary(midbest1) #ambient variable may not have strong influence over CO emission 
vif(midbest1)
midbest2 <-lm(CO ~. -AT-CDP-GTEP, data = gt_mid)
summary(midbest2)
vif(midbest2)
```



```{r}
# Removing influential observations
cd = cooks.distance(midbest2)
length(cd[which(cd > 4 / length(cd))])
midbest1a = lm(CO ~ AT + AP + AH + poly(AFDP,2) + poly(TIT,2) + poly(TAT,2) + poly(CDP,2), data = gt_mid, subset = cd <= 4 / length(cd))
summary(midbest1a)
vif(midbest1a)
```

```{r}
# Percentage of influential points in mid-range data
length(cd[which(cd > 4 / length(cd))])/nobs(midbest2)*100
```

```{r}
full = lm(CO ~ ., data = gt_mid)
fit1 = update(full, .~.-GTEP-AT-TIT)
j_model = lm(CO ~ poly(AP,2)+poly(AH,2) + poly(AFDP,2)+poly(TAT,2)+poly(TIT,2) + poly(TEY,2), data= gt_adj)
summary(j_model)
```

```{r Jonas model}
gt_bic_sel = function(df, full){
  all_mod = summary(regsubsets(CO ~ ., data=df, nvmax=11, method='exhaustive'))
  p = length(coef(full))
  n = length(resid(full))
  mod_bic = n*log(all_mod$rss/n) + log(n)*(2:p)
  m = which.min(mod_bic)
  all_mod$which[m,]
}

gt_adj_all = gt_mid_all[-c(out_ind)[c(3, 8)],]

full1 = lm(CO ~ ., data = gt_mid_all)

fit1 = update(full1, .~.-GTEP-AT-TIT)
run_all_diagnostic(fit1)
v = vif(fit1)
v[which(v > 5)]

gt_bic_sel(gt_mid_all, full1)
bic_mod1 = update(full1, .~.-CDP)
run_all_diagnostic(bic_mod1)

v = vif(bic_mod1)
v[which(v > 5)]

bic_mod2 = update(bic_mod1, .~.-GTEP-AT) # Leaving TIT in
run_all_diagnostic(bic_mod2)

v = vif(bic_mod2)
v[which(v > 5)]

fit_adj = update(fit1, data=gt_adj_all)
run_all_diagnostic(fit_adj)
bic_adj = update(bic_mod2, data=gt_adj_all)
run_all_diagnostic(bic_adj)

fit_refit = lm(sqrt(CO) ~ poly(AP,2)+poly(AH,2) + poly(AFDP,2)+poly(TAT,2)+poly(CDP,2) + poly(TEY,2) + poly(NOX,2), data=gt_mid_all)
run_all_diagnostic(fit_refit)

bic_refit = lm(sqrt(CO) ~ poly(AP,2)+poly(AH,2) + poly(AFDP,2)+poly(TAT,2)+poly(TIT,2) + poly(TEY,2) + poly(NOX,2), data=gt_mid_all)
run_all_diagnostic(bic_refit)

# Include these models for comparisons with -NOX model (Could be useful for client to see).
# Highest adj. R squared models for mid-range data.
j_mod = lm(sqrt(CO) ~ poly(AP,2)+poly(AT,2)+poly(AH,2) + poly(AFDP,2)+poly(TAT,2)+poly(TIT,2) + poly(TEY,2) + poly(NOX,2), data = gt_mid_all)
summary(j_mod)

j_mod1 = lm(sqrt(CO) ~ AT + AP + AH + poly(AFDP,2) + poly(TIT,2) + poly(TAT,2) + poly(CDP,2) + poly(TEY,2) + poly(NOX,2) ,data = gt_mid_all)
summary(j_mod1)
```





