---
title: 'STAT 443 Consulting Project Data Analysis'
author: "W. Jonas Reger"
date: "03/09/2021"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
```

```{r}
set.seed(1)
options(warn = -1)
suppressMessages(library(tidyverse))
suppressMessages(library(modelr))
suppressMessages(library(caret))
suppressMessages(library(broom))
suppressMessages(library(leaps))
suppressMessages(library(MASS))


```

## Data

Variables:

1. Ambient temperature (AT) C
2. Ambient pressure (AP) mbar
3. Ambient humidity (AH) (%)
4. Air filter difference pressure (AFDP) mbar
5. Gas turbine exhaust pressure (GTEP) mbar
6. Turbine inlet temperature (TIT) C
7. Turbine after temperature (TAT) C
8. Compressor discharge pressure (CDP) mbar
9. Turbine energy yield (TEY) MWH
10. Carbon monoxide (CO) mg/m3
11. Nitrogen oxides (NOX) mg/m3

```{r}
gt = read.csv('gt_2012.csv', sep = ',')
head(gt)
# sample_n(gt, 3)
summary(gt)

intmod = lm(CO ~ 1, data = gt)
full = lm(CO ~ ., data = gt)
summary(full)

glance(full) %>%
  dplyr::select(adj.r.squared, sigma, AIC, BIC, p.value)

predictions <- full %>% predict(gt)
data.frame(
  R2 = R2(predictions, gt$CO),
  RMSE = RMSE(predictions, gt$CO),
  MAE = MAE(predictions, gt$CO)
)

# AIC
aic.both = stepAIC(intmod, direction = 'both', scope = list(upper=full, lower=intmod), trace = FALSE)
aic.back = stepAIC(full, direction = 'backward', trace = FALSE)
aic.for = stepAIC(intmod, direction = 'forward', scope = list(upper=full, lower=intmod), trace = FALSE)

# BIC
bic.both = step(intmod, direction="both", k=log(nrow(gt)), scope=list(lower = intmod, upper = full), data=gt, trace = FALSE)
bic.back = step(full, direction="backward", k=log(nrow(gt)), scope=list(lower = intmod, upper = full), data=gt, trace = FALSE)
bic.for = step(intmod, direction="forward", k=log(nrow(gt)), scope=list(lower = intmod, upper = full), data=gt, trace = FALSE)

# Removed AP, AFDP, CDP, TEY, 
fit1 = lm(CO ~ AH + AT + GTEP + NOX + TAT + TIT, data = gt)
summary(fit1)
```


## Training

```{r}
# Load packages
suppressMessages(library(tibble))
set.seed(443)

# gt data as tibble
gte = as_tibble(gt)

# test-train split
gte_trn_idx = sample(nrow(gte), size = 0.8*nrow(gte))
gte_trn = gte[gte_trn_idx, ]
gte_tst = gte[-gte_trn_idx, ]

# estimation-validation split
gte_est_idx = sample(nrow(gte_trn), size = 0.8*nrow(gte_trn))
gte_est = gte_trn[gte_est_idx, ]
gte_val = gte_trn[-gte_est_idx, ]

# check data
head(gte_trn)
```



```{r}
mod = lm(CO ~ AH + AT + GTEP + NOX + TAT + TIT, data = gte_trn)
summary(mod)
```

```{r}
calc_rmse = function(actual, predicted){
  rmse = sqrt(mean((actual - predicted)^2))
  return(rmse)
}

calc_mae = function(actual, predicted){
  mae = mean(abs(actual-predicted))
  return(mae)
}

rmse_trn = calc_rmse(
  gte_est$CO, 
  predict(update(mod, data = gte_est), gte_est))
rmse_val = calc_rmse(
  gte_val$CO, 
  predict(update(mod, data = gte_est), gte_val))
rmse_tst = calc_rmse(
  gte_tst$CO, 
  predict(update(mod, data = gte_trn), gte_tst))

mae_trn = calc_mae(
  gte_est$CO, 
  predict(update(mod, data = gte_est), gte_est))
mae_val = calc_mae(
  gte_val$CO, 
  predict(update(mod, data = gte_est), gte_val))
mae_tst = calc_mae(
  gte_tst$CO, 
  predict(update(mod, data = gte_trn), gte_tst))

c(rmse_trn, rmse_val, rmse_tst)

c(mae_trn, mae_val, mae_tst)
```

```{r}
mod = lm(CO ~ AH + AT + GTEP + NOX + TAT + TIT, data = gte_trn)

fit2 = lm(CO ~ AH + AT, data = gte_trn)
fit3 = lm(CO ~ AH + AT + GTEP + TAT + TIT, data = gte_trn)
fit4 = lm(CO ~ AH + AT + GTEP + TAT + TIT + TEY, data = gte_trn)
fit5 = lm(CO ~ AH + AT + GTEP + TAT + TIT + TEY + NOX, data = gte_trn)

rmse_val2 = calc_rmse(
  gte_val$CO, 
  predict(update(fit2, data = gte_est), gte_val))
rmse_val3 = calc_rmse(
  gte_val$CO, 
  predict(update(fit3, data = gte_est), gte_val))
rmse_val4 = calc_rmse(
  gte_val$CO, 
  predict(update(fit4, data = gte_est), gte_val))
rmse_val5 = calc_rmse(
  gte_val$CO, 
  predict(update(fit5, data = gte_est), gte_val))

c(rmse_val2, rmse_val3, rmse_val4, rmse_val5)

rmse_tst5 = calc_rmse(
  gte_tst$CO, 
  predict(update(fit5, data = gte_trn), gte_tst))

rmse_tst5
```

```{r}
avg = c(mean(gte_trn$AH), mean(gte_trn$AT), mean(gte_trn$GTEP), mean(gte_trn$TAT), mean(gte_trn$TIT), mean(gte_trn$TEY), mean(gte_trn$NOX))

est = predict(fit5, data.frame(AH = avg[1], AT = avg[2], GTEP = avg[3], TAT = avg[4], TIT = avg[5], TEY = avg[6], NOX = avg[7]), interval = "confidence", level = 0.95)

pred = predict(fit5, data.frame(AH = avg[1], AT = avg[2], GTEP = avg[3], TAT = avg[4], TIT = avg[5], TEY = avg[6], NOX = avg[7]), interval = "prediction", level = 0.95)

est

pred
```

```{r}
plot(fit5)
```

```{r}
pairs(gt)
```














